version: '3.7'
services:
  recsys_path:
    image: "tatsuki1107/python_poetry"
    container_name: recsys_container
    volumes:
      - .:/app/work
    ports:
      - 8888:8888
    tty: true
    command: poetry run jupyter lab --allow-root --ip=0.0.0.0 --LabApp.token=""
